### ISSUE TITLE
please: command not found

### ISSUE THREAD

**Issue by yash-10x** [NayamAmarshe/please#42]
![Screenshot (3)](https://user-images.githubusercontent.com/98729131/220269298-12aaea7a-208e-49db-9aa8-6944231b82df.png)

**Comment by NayamAmarshe** [comment]
You're on Windows. I have no idea how to do it on there tbh but read this: https://github.com/NayamAmarshe/please#-troubleshooting

**Comment by dankuri** [comment]
@NayamAmarshe yash-10x is actually using wsl ubuntu, so the process should be the same as linux. I've tried to fresh install it on wsl with `pip install please-cli` and it worked fine. @yash-10x can you share, how did you install it? Probably the problem is with `$PATH`, so linked solution should fix the error. Remember to put `please` at the end of `.bashrc`

**Comment by yash-10x** [comment]
Thank you

**Comment by wolfdave** [comment]
I use zsh on WSL. I had to add `export PATH="$PATH:$HOME/.local/bin"` to my .zshrc like in your troubleshooting explained.
